### PR TITLE
BFE coefficients from file

### PR DESCRIPTION
**Pull request by SaraRegibo**
These changes somehow never made it to the `develop` branch.

- coefficients `a_ij^X` are now read from a file (see #434 )
- problem with the flux conservation (see #399)
- validation of the BFE

### CODE REVIEW

**Comment by SaraRegibo** [comment]
@s-geiser, would you mind reviewing this pull request?  These changes somehow never made it to the `develop` branch (sorry about that).  Thanks!

**Review by s-geiser — COMMENTED** [review]
I am no expert on the BFE topic but the behavior is a little weird to me:

I ran a test with a single magnitude 11 star close to the middle of the subfield, with all effects turned off except BFE (one run with BFE, one run without, code obtained from your GitHub).

- The total Flux is now well conserved, both cases having the same summed flux in a (generous) 10x10 mask around the star (mask size chosen so that all pixels with Fpix > Fbackground are considered)

- The maximum value (peak flux in central pixel) is reduced when taking the BFE into account, as is expected due to the redistriution

- The shape of the redistribution on the other had is weird: it is a clear bipole, flux from ALL top half pixels being moved to ALL bottom half pixels, instead of a circular pattern (see image below)

image

I attached the excel file with all the values as well: [BFE.xlsx](https://github.com/IvS-KULeuven/PlatoSim3/files/4716104/BFE.xlsx)

An example of the circular redistribution can be seen here (from [Hirata & Choi 2019], https://arxiv.org/abs/1906.01846)

image

A different small comment: in Detector.h, the #include block is repeated for the integralOfAnalyticSignalResponse class.

I am sorry not to have seen this earlier, I just checked the total sum and maximum value in the quick test when you made the changes a while back.

**Comment by SaraRegibo** [comment]
@s-geiser Thanks for your review.  I just found the cause of this weird re-distribution of the flux.  It's included in the pull request.

**Review by s-geiser — APPROVED** [review]
Works perfectly now.

Energy still conserved, but pattern now moving electrons outward:

image

**Pull request merged**
