### PR TITLE
Implement mechanical vignetting

### PR DESCRIPTION
**Pull request by SaraRegibo**
Implementation of GitHub issue #334 

* What was called "vignetting" before is now referred to as "natural vignetting".  The implementation of this brightness attenuation towards the edge of the FOV remains the same as before.  The structure of the block configuring the vignetting in the input files has been changed.
* Mechanical vignetting: all incoming flux (apart from cosmic hits) is shielded off beyond 18.8876 degrees away from the optical axis (so outside of the FOV).  Note that this implementation does not exactly coincide with  Fig. 11 in PLATO-INAF-PL-RP-001 (Telescope Optical Units Performance Analysis report), as the smooth loss in efficiency from about 15 degrees from the OA has not been implemented.
* Updated the expected value for the efficiency for the natural vignetting (0.945 instead of 0.904), as this had been copied incorrectly from reference documents.
* Natural and mechanical vignetting can be enabled/disabled separately.
* The implementation of mechanical vignetting required revisiting the implementation of the open-shutter smearing.  In case part of a column falls outside the FOV, the open-shutter smearing will affect this column for a shorter period of time (because it cannot affect the pixels that are shielded off outside the FOV).  The calculation of the mean accumulated flux (to calculate the open-shutter smearing) is done only for the pixels inside the FOV.
* Updated all input files, Python scripts, and tutorials.
* Updated documentation.
* The description of the algorithm in TN007 still needs to be done.

### CODE REVIEW

**Comment by JorisDeRidder** [comment]
Can't accept pull request because of the many conflicts.

**Review by JorisDeRidder — COMMENTED** [review]
In all yaml files in the section Vignetting, can you please add  after "Natural vignetting" the comment "Brightness attenuation from the optical axis to the edge of the FOV" and after "Mechanical vignetting" the comment "Blocking of the light due to mechanical obstruction at the edge of the FOV"?

**Comment by SaraRegibo** [comment]
I'll look into the merge conflicts!

**Comment by SaraRegibo** [comment]
* Manually resolved merge conflicts.
* Added comments in the configuration files explaining what natural and mechanical vignetting are.

**Pull request merged**
