### PR TITLE
Introducing a picsim alternative that generates catalogues from a named source

### PR DESCRIPTION
**Pull request by Nagromancer**
I have written an alternative version of picsim, which, rather than generating a random catalogue, produces a target file with one star (given by the user) and generates the corresponding contaminants file. The output format is the same as picsim and is, therefore, compatible with platonium.

I created a new script for simplicity rather than modifying the existing picsim. As a result, there is some amount of duplication. This was preferable to spaghettifying the picsim script.

Some example outputs are shown below:

Successful execution:

Screenshot 2023-02-20 at 10 58 48

Entering a target that doesn't exist in Gaia's database:

Screenshot 2023-02-17 at 16 51 06

Entering a real Gaia target that's not in the PIC (could also be in the PIC but removed due to NaN values of parameters):

Screenshot 2023-02-17 at 16 53 43

Using a bad output directory:

Screenshot 2023-02-17 at 16 55 03

I modified the utilities.py module to add a Gaia query function.

I also added a 10MB pickled dictionary relating Gaia DR2 IDs to PIC IDs. I would have preferred to generate this dictionary on the client side, but it would mean downloading a 1.4GB catalogue file and ~4 minutes generating it.

I look forward to your feedback!

### CODE REVIEW

**Comment by nicholasjannsen** [comment]
Hi Morgan, 

very nice work it's a cool feature to have!

Just a few things to consider:
- I changed most of the doc-strings in the python files using now lowercase letters for  "Parameters" and "Return" (minor detail).
- When you add a new library like `astroquery` we need to at it to the Conda and the Poetry installation method, otherwise our test suit (which you can find and run in `PlatoSim3/tests/validationTests/scripts/run.py`) will fail and the same story for the user, as `utilities.py` is used e.g. by the `simulation.py` and `simfile.py`. No worries, just mention it to me/us and we can add it, if it's an important and light package (as it is here). I'll add it ASAP and merge your commit.
- You should generally not be using pickle objects since they are dependent on the Python version. From my understanding this is not the case for numpy or feather objects. E.g. I save everything in either of these formats since they are far the best for I/O writing with `pandas`. 
- I would prefer not have 10 Mb extra to download when you fetch PlatoSim from our github. Instead upload it to our KU Leuven FTP server and add a small `if` statement that automatically download the data upon a first execution with `picsim`. You can more or less copy the code from line 250 in `picsim` and if you have any troubles uploading the 10 Mb file to our FTP server, let me know and I can help you.

**Comment by Nagromancer** [comment]
Hi Nicholas,

Thank you for your detailed and constructive feedback. I was unsure about pickling, so I'm happy to remove it.

I have removed the block capitalization of "parameters" and "returns" from the docstrings.

I have replaced the .pkl object with a .npy array, and the dictionary is generated dynamically on the client side (taking about 0.12 seconds to do so). However, I would appreciate some help getting the .npy file onto your FTP server.

Please also add astroquery to the dependencies.

Once the array is uploaded, all of your points will have been addressed :)

**Comment by nicholasjannsen** [comment]
Looks great! Just send me the numpy file over email and I'll add it to the FTP server. I'll merge as soon as I have added `astroquery` to the dependencies.

**Comment by nicholasjannsen** [comment]
I have added `astroquery` to the Poetry install instead of the Conda installation to make the installation of PlatoSim have as few dependencies as possible. There is a small problem with the FTP server, but I will upload the file early next week.

**Comment by nicholasjannsen** [comment]
Worked flawlessly @Nagromancer  - nice work!
Screenshot from 2023-02-27 18-39-26

**Pull request merged**
