### PR TITLE
Fixed bug in rotation matrix concerning the camera tilt angle.

### PR DESCRIPTION
**Pull request by JorisDeRidder**
It concerns a sign error in matrix (A7) in the paper of Jannsen et al. (2023).
Corrections were made both in the C++ and the Python code.

### CODE REVIEW

**Comment by drsamadi** [comment]
Hi Joris,
do you mean that the formula A7 given in Jannsen et al. (2023) was wrong or its implementation into PLATOSim was wrong ?
With this correction I understand that we go back to the definition that were since a long time, right ?

**Comment by drsamadi** [comment]
here attached the version of the paper I get from axrxiv
[2310.06985.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/13072898/2310.06985.pdf)

Eq. A7  has as sign opposed to the one coded in the new commit (  #903)

**Comment by JorisDeRidder** [comment]
Before this commit, the code and the article were in agreement but both were wrong. After this commit, the rotation matrix of the tilt angle in the code (both C++ and Python) is corrected, but it seems unlikely that we will still be able to also correct the corresponding Eq (A7) in the paper since the paper is already at such a late stage at A&A. I will at least update KUL-TN-001 as soon as possible.

**Comment by drsamadi** [comment]
OK thanks for the clarification !

**Pull request merged**
